CREATE TABLE IF NOT EXISTS Persons (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Email TEXT NOT NULL UNIQUE,
    Name TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS IX_Persons_Email ON Persons (Email);
